
namespace Sasco
{
    partial class ForgotPassword
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ForgotPassword));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.activateBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.loginNameEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.tokencode = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.conpassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.password = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.save = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.loginname = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.closebtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPages1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPages1
            // 
            this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.bunifuPages1.AllowTransitions = true;
            this.bunifuPages1.Controls.Add(this.tabPage1);
            this.bunifuPages1.Controls.Add(this.tabPage2);
            this.bunifuPages1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPages1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPages1.Multiline = true;
            this.bunifuPages1.Name = "bunifuPages1";
            this.bunifuPages1.Page = this.tabPage1;
            this.bunifuPages1.PageIndex = 0;
            this.bunifuPages1.PageName = "tabPage1";
            this.bunifuPages1.PageTitle = "tabPage1";
            this.bunifuPages1.SelectedIndex = 0;
            this.bunifuPages1.Size = new System.Drawing.Size(518, 530);
            this.bunifuPages1.TabIndex = 1;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.bunifuPages1.Transition = animation1;
            this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.HorizSlide;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.MidnightBlue;
            this.tabPage1.Controls.Add(this.bunifuButton21);
            this.tabPage1.Controls.Add(this.bunifuLabel7);
            this.tabPage1.Controls.Add(this.activateBtn);
            this.tabPage1.Controls.Add(this.loginNameEmail);
            this.tabPage1.Controls.Add(this.bunifuLabel3);
            this.tabPage1.Location = new System.Drawing.Point(4, 4);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(510, 504);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "tabPage1";
            // 
            // activateBtn
            // 
            this.activateBtn.AllowAnimations = true;
            this.activateBtn.AllowMouseEffects = true;
            this.activateBtn.AllowToggling = false;
            this.activateBtn.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.activateBtn.AnimationSpeed = 200;
            this.activateBtn.AutoGenerateColors = false;
            this.activateBtn.AutoRoundBorders = false;
            this.activateBtn.AutoSizeLeftIcon = true;
            this.activateBtn.AutoSizeRightIcon = true;
            this.activateBtn.BackColor = System.Drawing.Color.Transparent;
            this.activateBtn.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.activateBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("activateBtn.BackgroundImage")));
            this.activateBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.activateBtn.ButtonText = "Send Email";
            this.activateBtn.ButtonTextMarginLeft = 0;
            this.activateBtn.ColorContrastOnClick = 45;
            this.activateBtn.ColorContrastOnHover = 45;
            this.activateBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.activateBtn.CustomizableEdges = borderEdges2;
            this.activateBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.activateBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.activateBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.activateBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.activateBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.activateBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.activateBtn.ForeColor = System.Drawing.Color.White;
            this.activateBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.activateBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.activateBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.activateBtn.IconMarginLeft = 11;
            this.activateBtn.IconPadding = 10;
            this.activateBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.activateBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.activateBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.activateBtn.IconSize = 25;
            this.activateBtn.IdleBorderColor = System.Drawing.Color.Black;
            this.activateBtn.IdleBorderRadius = 1;
            this.activateBtn.IdleBorderThickness = 1;
            this.activateBtn.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.activateBtn.IdleIconLeftImage = null;
            this.activateBtn.IdleIconRightImage = null;
            this.activateBtn.IndicateFocus = false;
            this.activateBtn.Location = new System.Drawing.Point(206, 238);
            this.activateBtn.Name = "activateBtn";
            this.activateBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.activateBtn.OnDisabledState.BorderRadius = 1;
            this.activateBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.activateBtn.OnDisabledState.BorderThickness = 1;
            this.activateBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.activateBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.activateBtn.OnDisabledState.IconLeftImage = null;
            this.activateBtn.OnDisabledState.IconRightImage = null;
            this.activateBtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.activateBtn.onHoverState.BorderRadius = 1;
            this.activateBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.activateBtn.onHoverState.BorderThickness = 1;
            this.activateBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.activateBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.activateBtn.onHoverState.IconLeftImage = null;
            this.activateBtn.onHoverState.IconRightImage = null;
            this.activateBtn.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.activateBtn.OnIdleState.BorderRadius = 1;
            this.activateBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.activateBtn.OnIdleState.BorderThickness = 1;
            this.activateBtn.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.activateBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.activateBtn.OnIdleState.IconLeftImage = null;
            this.activateBtn.OnIdleState.IconRightImage = null;
            this.activateBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.activateBtn.OnPressedState.BorderRadius = 1;
            this.activateBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.activateBtn.OnPressedState.BorderThickness = 1;
            this.activateBtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.activateBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.activateBtn.OnPressedState.IconLeftImage = null;
            this.activateBtn.OnPressedState.IconRightImage = null;
            this.activateBtn.Size = new System.Drawing.Size(94, 39);
            this.activateBtn.TabIndex = 9;
            this.activateBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.activateBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.activateBtn.TextMarginLeft = 0;
            this.activateBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.activateBtn.UseDefaultRadiusAndThickness = true;
            this.activateBtn.Click += new System.EventHandler(this.activateBtn_Click);
            // 
            // loginNameEmail
            // 
            this.loginNameEmail.AcceptsReturn = false;
            this.loginNameEmail.AcceptsTab = false;
            this.loginNameEmail.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.loginNameEmail.AnimationSpeed = 200;
            this.loginNameEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.loginNameEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.loginNameEmail.AutoSizeHeight = true;
            this.loginNameEmail.BackColor = System.Drawing.Color.Transparent;
            this.loginNameEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loginNameEmail.BackgroundImage")));
            this.loginNameEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.loginNameEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loginNameEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.loginNameEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.loginNameEmail.BorderRadius = 1;
            this.loginNameEmail.BorderThickness = 1;
            this.loginNameEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.loginNameEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.loginNameEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.loginNameEmail.DefaultText = "";
            this.loginNameEmail.FillColor = System.Drawing.Color.White;
            this.loginNameEmail.ForeColor = System.Drawing.Color.Black;
            this.loginNameEmail.HideSelection = true;
            this.loginNameEmail.IconLeft = null;
            this.loginNameEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginNameEmail.IconPadding = 10;
            this.loginNameEmail.IconRight = null;
            this.loginNameEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginNameEmail.Lines = new string[0];
            this.loginNameEmail.Location = new System.Drawing.Point(88, 190);
            this.loginNameEmail.MaxLength = 32767;
            this.loginNameEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.loginNameEmail.Modified = false;
            this.loginNameEmail.Multiline = false;
            this.loginNameEmail.Name = "loginNameEmail";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginNameEmail.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.loginNameEmail.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginNameEmail.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginNameEmail.OnIdleState = stateProperties4;
            this.loginNameEmail.Padding = new System.Windows.Forms.Padding(3);
            this.loginNameEmail.PasswordChar = '\0';
            this.loginNameEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.loginNameEmail.PlaceholderText = "Enter Login Name";
            this.loginNameEmail.ReadOnly = false;
            this.loginNameEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.loginNameEmail.SelectedText = "";
            this.loginNameEmail.SelectionLength = 0;
            this.loginNameEmail.SelectionStart = 0;
            this.loginNameEmail.ShortcutsEnabled = true;
            this.loginNameEmail.Size = new System.Drawing.Size(334, 42);
            this.loginNameEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.loginNameEmail.TabIndex = 8;
            this.loginNameEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.loginNameEmail.TextMarginBottom = 0;
            this.loginNameEmail.TextMarginLeft = 3;
            this.loginNameEmail.TextMarginTop = 1;
            this.loginNameEmail.TextPlaceholder = "Enter Login Name";
            this.loginNameEmail.UseSystemPasswordChar = false;
            this.loginNameEmail.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 15F);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(87, 156);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(106, 28);
            this.bunifuLabel3.TabIndex = 7;
            this.bunifuLabel3.Text = "Login Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.MidnightBlue;
            this.tabPage2.Controls.Add(this.closebtn);
            this.tabPage2.Controls.Add(this.bunifuLabel6);
            this.tabPage2.Controls.Add(this.tokencode);
            this.tabPage2.Controls.Add(this.bunifuLabel5);
            this.tabPage2.Controls.Add(this.conpassword);
            this.tabPage2.Controls.Add(this.bunifuLabel4);
            this.tabPage2.Controls.Add(this.password);
            this.tabPage2.Controls.Add(this.bunifuLabel2);
            this.tabPage2.Controls.Add(this.save);
            this.tabPage2.Controls.Add(this.loginname);
            this.tabPage2.Controls.Add(this.bunifuLabel1);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(510, 504);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            // 
            // tokencode
            // 
            this.tokencode.AcceptsReturn = false;
            this.tokencode.AcceptsTab = false;
            this.tokencode.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.tokencode.AnimationSpeed = 200;
            this.tokencode.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tokencode.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tokencode.AutoSizeHeight = true;
            this.tokencode.BackColor = System.Drawing.Color.Transparent;
            this.tokencode.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tokencode.BackgroundImage")));
            this.tokencode.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tokencode.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tokencode.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tokencode.BorderColorIdle = System.Drawing.Color.Silver;
            this.tokencode.BorderRadius = 1;
            this.tokencode.BorderThickness = 1;
            this.tokencode.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tokencode.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tokencode.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.tokencode.DefaultText = "";
            this.tokencode.FillColor = System.Drawing.Color.White;
            this.tokencode.ForeColor = System.Drawing.Color.Black;
            this.tokencode.HideSelection = true;
            this.tokencode.IconLeft = null;
            this.tokencode.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tokencode.IconPadding = 10;
            this.tokencode.IconRight = null;
            this.tokencode.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tokencode.Lines = new string[0];
            this.tokencode.Location = new System.Drawing.Point(94, 204);
            this.tokencode.MaxLength = 32767;
            this.tokencode.MinimumSize = new System.Drawing.Size(1, 1);
            this.tokencode.Modified = false;
            this.tokencode.Multiline = false;
            this.tokencode.Name = "tokencode";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tokencode.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tokencode.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tokencode.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tokencode.OnIdleState = stateProperties8;
            this.tokencode.Padding = new System.Windows.Forms.Padding(3);
            this.tokencode.PasswordChar = '\0';
            this.tokencode.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tokencode.PlaceholderText = "Enter Code";
            this.tokencode.ReadOnly = false;
            this.tokencode.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tokencode.SelectedText = "";
            this.tokencode.SelectionLength = 0;
            this.tokencode.SelectionStart = 0;
            this.tokencode.ShortcutsEnabled = true;
            this.tokencode.Size = new System.Drawing.Size(334, 42);
            this.tokencode.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tokencode.TabIndex = 18;
            this.tokencode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tokencode.TextMarginBottom = 0;
            this.tokencode.TextMarginLeft = 3;
            this.tokencode.TextMarginTop = 1;
            this.tokencode.TextPlaceholder = "Enter Code";
            this.tokencode.UseSystemPasswordChar = false;
            this.tokencode.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Segoe UI", 15F);
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(93, 170);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(46, 28);
            this.bunifuLabel5.TabIndex = 17;
            this.bunifuLabel5.Text = "Code";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // conpassword
            // 
            this.conpassword.AcceptsReturn = false;
            this.conpassword.AcceptsTab = false;
            this.conpassword.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.conpassword.AnimationSpeed = 200;
            this.conpassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.conpassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.conpassword.AutoSizeHeight = true;
            this.conpassword.BackColor = System.Drawing.Color.Transparent;
            this.conpassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("conpassword.BackgroundImage")));
            this.conpassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.conpassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.conpassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.conpassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.conpassword.BorderRadius = 1;
            this.conpassword.BorderThickness = 1;
            this.conpassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.conpassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.conpassword.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.conpassword.DefaultText = "";
            this.conpassword.FillColor = System.Drawing.Color.White;
            this.conpassword.ForeColor = System.Drawing.Color.Black;
            this.conpassword.HideSelection = true;
            this.conpassword.IconLeft = null;
            this.conpassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.conpassword.IconPadding = 10;
            this.conpassword.IconRight = null;
            this.conpassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.conpassword.Lines = new string[0];
            this.conpassword.Location = new System.Drawing.Point(95, 400);
            this.conpassword.MaxLength = 32767;
            this.conpassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.conpassword.Modified = false;
            this.conpassword.Multiline = false;
            this.conpassword.Name = "conpassword";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.conpassword.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.conpassword.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.conpassword.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.conpassword.OnIdleState = stateProperties12;
            this.conpassword.Padding = new System.Windows.Forms.Padding(3);
            this.conpassword.PasswordChar = '\0';
            this.conpassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.conpassword.PlaceholderText = "Enter Password";
            this.conpassword.ReadOnly = false;
            this.conpassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.conpassword.SelectedText = "";
            this.conpassword.SelectionLength = 0;
            this.conpassword.SelectionStart = 0;
            this.conpassword.ShortcutsEnabled = true;
            this.conpassword.Size = new System.Drawing.Size(334, 42);
            this.conpassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.conpassword.TabIndex = 16;
            this.conpassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.conpassword.TextMarginBottom = 0;
            this.conpassword.TextMarginLeft = 3;
            this.conpassword.TextMarginTop = 1;
            this.conpassword.TextPlaceholder = "Enter Password";
            this.conpassword.UseSystemPasswordChar = false;
            this.conpassword.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 15F);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(94, 366);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(157, 28);
            this.bunifuLabel4.TabIndex = 15;
            this.bunifuLabel4.Text = "Confirm Password";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // password
            // 
            this.password.AcceptsReturn = false;
            this.password.AcceptsTab = false;
            this.password.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.password.AnimationSpeed = 200;
            this.password.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.password.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.password.AutoSizeHeight = true;
            this.password.BackColor = System.Drawing.Color.Transparent;
            this.password.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("password.BackgroundImage")));
            this.password.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.password.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.password.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.password.BorderColorIdle = System.Drawing.Color.Silver;
            this.password.BorderRadius = 1;
            this.password.BorderThickness = 1;
            this.password.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.password.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.password.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.password.DefaultText = "";
            this.password.FillColor = System.Drawing.Color.White;
            this.password.ForeColor = System.Drawing.Color.Black;
            this.password.HideSelection = true;
            this.password.IconLeft = null;
            this.password.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.password.IconPadding = 10;
            this.password.IconRight = null;
            this.password.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.password.Lines = new string[0];
            this.password.Location = new System.Drawing.Point(94, 299);
            this.password.MaxLength = 32767;
            this.password.MinimumSize = new System.Drawing.Size(1, 1);
            this.password.Modified = false;
            this.password.Multiline = false;
            this.password.Name = "password";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.password.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password.OnIdleState = stateProperties16;
            this.password.Padding = new System.Windows.Forms.Padding(3);
            this.password.PasswordChar = '\0';
            this.password.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.password.PlaceholderText = "Enter Password";
            this.password.ReadOnly = false;
            this.password.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.password.SelectedText = "";
            this.password.SelectionLength = 0;
            this.password.SelectionStart = 0;
            this.password.ShortcutsEnabled = true;
            this.password.Size = new System.Drawing.Size(334, 42);
            this.password.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.password.TabIndex = 14;
            this.password.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.password.TextMarginBottom = 0;
            this.password.TextMarginLeft = 3;
            this.password.TextMarginTop = 1;
            this.password.TextPlaceholder = "Enter Password";
            this.password.UseSystemPasswordChar = false;
            this.password.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 15F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(93, 265);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(82, 28);
            this.bunifuLabel2.TabIndex = 13;
            this.bunifuLabel2.Text = "Password";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // save
            // 
            this.save.AllowAnimations = true;
            this.save.AllowMouseEffects = true;
            this.save.AllowToggling = false;
            this.save.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.save.AnimationSpeed = 200;
            this.save.AutoGenerateColors = false;
            this.save.AutoRoundBorders = false;
            this.save.AutoSizeLeftIcon = true;
            this.save.AutoSizeRightIcon = true;
            this.save.BackColor = System.Drawing.Color.Transparent;
            this.save.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.save.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("save.BackgroundImage")));
            this.save.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save.ButtonText = "Set Password";
            this.save.ButtonTextMarginLeft = 0;
            this.save.ColorContrastOnClick = 45;
            this.save.ColorContrastOnHover = 45;
            this.save.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.save.CustomizableEdges = borderEdges4;
            this.save.DialogResult = System.Windows.Forms.DialogResult.None;
            this.save.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.save.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.save.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.save.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.save.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.save.ForeColor = System.Drawing.Color.White;
            this.save.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.save.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.save.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.save.IconMarginLeft = 11;
            this.save.IconPadding = 10;
            this.save.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.save.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.save.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.save.IconSize = 25;
            this.save.IdleBorderColor = System.Drawing.Color.Black;
            this.save.IdleBorderRadius = 1;
            this.save.IdleBorderThickness = 1;
            this.save.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.save.IdleIconLeftImage = null;
            this.save.IdleIconRightImage = null;
            this.save.IndicateFocus = false;
            this.save.Location = new System.Drawing.Point(220, 448);
            this.save.Name = "save";
            this.save.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.save.OnDisabledState.BorderRadius = 1;
            this.save.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save.OnDisabledState.BorderThickness = 1;
            this.save.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.save.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.save.OnDisabledState.IconLeftImage = null;
            this.save.OnDisabledState.IconRightImage = null;
            this.save.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.save.onHoverState.BorderRadius = 1;
            this.save.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save.onHoverState.BorderThickness = 1;
            this.save.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.save.onHoverState.ForeColor = System.Drawing.Color.White;
            this.save.onHoverState.IconLeftImage = null;
            this.save.onHoverState.IconRightImage = null;
            this.save.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.save.OnIdleState.BorderRadius = 1;
            this.save.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save.OnIdleState.BorderThickness = 1;
            this.save.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.save.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.save.OnIdleState.IconLeftImage = null;
            this.save.OnIdleState.IconRightImage = null;
            this.save.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.save.OnPressedState.BorderRadius = 1;
            this.save.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.save.OnPressedState.BorderThickness = 1;
            this.save.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.save.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.save.OnPressedState.IconLeftImage = null;
            this.save.OnPressedState.IconRightImage = null;
            this.save.Size = new System.Drawing.Size(94, 39);
            this.save.TabIndex = 12;
            this.save.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.save.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.save.TextMarginLeft = 0;
            this.save.TextPadding = new System.Windows.Forms.Padding(0);
            this.save.UseDefaultRadiusAndThickness = true;
            this.save.Click += new System.EventHandler(this.save_Click);
            // 
            // loginname
            // 
            this.loginname.AcceptsReturn = false;
            this.loginname.AcceptsTab = false;
            this.loginname.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.loginname.AnimationSpeed = 200;
            this.loginname.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.loginname.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.loginname.AutoSizeHeight = true;
            this.loginname.BackColor = System.Drawing.Color.Transparent;
            this.loginname.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("loginname.BackgroundImage")));
            this.loginname.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.loginname.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.loginname.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.loginname.BorderColorIdle = System.Drawing.Color.Silver;
            this.loginname.BorderRadius = 1;
            this.loginname.BorderThickness = 1;
            this.loginname.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.loginname.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.loginname.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.loginname.DefaultText = "";
            this.loginname.FillColor = System.Drawing.Color.White;
            this.loginname.ForeColor = System.Drawing.Color.Black;
            this.loginname.HideSelection = true;
            this.loginname.IconLeft = null;
            this.loginname.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginname.IconPadding = 10;
            this.loginname.IconRight = null;
            this.loginname.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.loginname.Lines = new string[0];
            this.loginname.Location = new System.Drawing.Point(95, 122);
            this.loginname.MaxLength = 32767;
            this.loginname.MinimumSize = new System.Drawing.Size(1, 1);
            this.loginname.Modified = false;
            this.loginname.Multiline = false;
            this.loginname.Name = "loginname";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginname.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.loginname.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginname.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.loginname.OnIdleState = stateProperties20;
            this.loginname.Padding = new System.Windows.Forms.Padding(3);
            this.loginname.PasswordChar = '\0';
            this.loginname.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.loginname.PlaceholderText = "Enter Login Name";
            this.loginname.ReadOnly = false;
            this.loginname.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.loginname.SelectedText = "";
            this.loginname.SelectionLength = 0;
            this.loginname.SelectionStart = 0;
            this.loginname.ShortcutsEnabled = true;
            this.loginname.Size = new System.Drawing.Size(334, 42);
            this.loginname.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.loginname.TabIndex = 11;
            this.loginname.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.loginname.TextMarginBottom = 0;
            this.loginname.TextMarginLeft = 3;
            this.loginname.TextMarginTop = 1;
            this.loginname.TextPlaceholder = "Enter Login Name";
            this.loginname.UseSystemPasswordChar = false;
            this.loginname.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 15F);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(95, 88);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(106, 28);
            this.bunifuLabel1.TabIndex = 10;
            this.bunifuLabel1.Text = "Login Name";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Segoe UI", 17F);
            this.bunifuLabel6.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.bunifuLabel6.Location = new System.Drawing.Point(165, 25);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(159, 31);
            this.bunifuLabel6.TabIndex = 19;
            this.bunifuLabel6.Text = "Reset Password";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Segoe UI", 17F);
            this.bunifuLabel7.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.bunifuLabel7.Location = new System.Drawing.Point(165, 25);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(170, 31);
            this.bunifuLabel7.TabIndex = 20;
            this.bunifuLabel7.Text = "Forgot Password";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // closebtn
            // 
            this.closebtn.AllowAnimations = true;
            this.closebtn.AllowMouseEffects = true;
            this.closebtn.AllowToggling = false;
            this.closebtn.AnimationSpeed = 200;
            this.closebtn.AutoGenerateColors = false;
            this.closebtn.AutoRoundBorders = false;
            this.closebtn.AutoSizeLeftIcon = true;
            this.closebtn.AutoSizeRightIcon = true;
            this.closebtn.BackColor = System.Drawing.Color.Transparent;
            this.closebtn.BackColor1 = System.Drawing.Color.DarkRed;
            this.closebtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("closebtn.BackgroundImage")));
            this.closebtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.closebtn.ButtonText = "Close";
            this.closebtn.ButtonTextMarginLeft = 0;
            this.closebtn.ColorContrastOnClick = 45;
            this.closebtn.ColorContrastOnHover = 45;
            this.closebtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.closebtn.CustomizableEdges = borderEdges3;
            this.closebtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.closebtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.closebtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.closebtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.closebtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.closebtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.closebtn.ForeColor = System.Drawing.Color.White;
            this.closebtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.closebtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.closebtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.closebtn.IconMarginLeft = 11;
            this.closebtn.IconPadding = 10;
            this.closebtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.closebtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.closebtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.closebtn.IconSize = 25;
            this.closebtn.IdleBorderColor = System.Drawing.Color.DarkRed;
            this.closebtn.IdleBorderRadius = 1;
            this.closebtn.IdleBorderThickness = 1;
            this.closebtn.IdleFillColor = System.Drawing.Color.DarkRed;
            this.closebtn.IdleIconLeftImage = null;
            this.closebtn.IdleIconRightImage = null;
            this.closebtn.IndicateFocus = false;
            this.closebtn.Location = new System.Drawing.Point(320, 448);
            this.closebtn.Name = "closebtn";
            this.closebtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.closebtn.OnDisabledState.BorderRadius = 1;
            this.closebtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.closebtn.OnDisabledState.BorderThickness = 1;
            this.closebtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.closebtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.closebtn.OnDisabledState.IconLeftImage = null;
            this.closebtn.OnDisabledState.IconRightImage = null;
            this.closebtn.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.closebtn.onHoverState.BorderRadius = 1;
            this.closebtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.closebtn.onHoverState.BorderThickness = 1;
            this.closebtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.closebtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.closebtn.onHoverState.IconLeftImage = null;
            this.closebtn.onHoverState.IconRightImage = null;
            this.closebtn.OnIdleState.BorderColor = System.Drawing.Color.DarkRed;
            this.closebtn.OnIdleState.BorderRadius = 1;
            this.closebtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.closebtn.OnIdleState.BorderThickness = 1;
            this.closebtn.OnIdleState.FillColor = System.Drawing.Color.DarkRed;
            this.closebtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.closebtn.OnIdleState.IconLeftImage = null;
            this.closebtn.OnIdleState.IconRightImage = null;
            this.closebtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.closebtn.OnPressedState.BorderRadius = 1;
            this.closebtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.closebtn.OnPressedState.BorderThickness = 1;
            this.closebtn.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.closebtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.closebtn.OnPressedState.IconLeftImage = null;
            this.closebtn.OnPressedState.IconRightImage = null;
            this.closebtn.Size = new System.Drawing.Size(108, 39);
            this.closebtn.TabIndex = 20;
            this.closebtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.closebtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.closebtn.TextMarginLeft = 0;
            this.closebtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.closebtn.UseDefaultRadiusAndThickness = true;
            this.closebtn.Click += new System.EventHandler(this.closebtn_Click);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.DarkRed;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Close";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges1;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.DarkRed;
            this.bunifuButton21.IdleBorderRadius = 1;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.DarkRed;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(314, 238);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 1;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 1;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.DarkRed;
            this.bunifuButton21.OnIdleState.BorderRadius = 1;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DarkRed;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 1;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(108, 39);
            this.bunifuButton21.TabIndex = 21;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // ForgotPassword
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(518, 530);
            this.Controls.Add(this.bunifuPages1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "ForgotPassword";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "ForgotPassword";
            this.bunifuPages1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
        private System.Windows.Forms.TabPage tabPage1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 activateBtn;
        private Bunifu.UI.WinForms.BunifuTextBox loginNameEmail;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuTextBox tokencode;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox conpassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox password;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 save;
        private Bunifu.UI.WinForms.BunifuTextBox loginname;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 closebtn;
    }
}